
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionUtilisateur", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionUtilisateur {


    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimer", targetNamespace = "http://service/", className = "service.Supprimer")
    @ResponseWrapper(localName = "supprimerResponse", targetNamespace = "http://service/", className = "service.SupprimerResponse")
    @Action(input = "http://service/GestionUtilisateur/supprimerRequest", output = "http://service/GestionUtilisateur/supprimerResponse")
    public Boolean supprimer(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param password
     * @param login
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouter", targetNamespace = "http://service/", className = "service.Ajouter")
    @ResponseWrapper(localName = "ajouterResponse", targetNamespace = "http://service/", className = "service.AjouterResponse")
    @Action(input = "http://service/GestionUtilisateur/ajouterRequest", output = "http://service/GestionUtilisateur/ajouterResponse")
    public Boolean ajouter(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param id
     * @param login
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifier", targetNamespace = "http://service/", className = "service.Modifier")
    @ResponseWrapper(localName = "modifierResponse", targetNamespace = "http://service/", className = "service.ModifierResponse")
    @Action(input = "http://service/GestionUtilisateur/modifierRequest", output = "http://service/GestionUtilisateur/modifierResponse")
    public Boolean modifier(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @return
     *     returns java.util.List<service.Utilisateur>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lister", targetNamespace = "http://service/", className = "service.Lister")
    @ResponseWrapper(localName = "listerResponse", targetNamespace = "http://service/", className = "service.ListerResponse")
    @Action(input = "http://service/GestionUtilisateur/listerRequest", output = "http://service/GestionUtilisateur/listerResponse")
    public List<Utilisateur> lister();

}
